### ISSUE TITLE
[Bug] Error syncing new dbt quickbooks transformation

### ISSUE THREAD

**Issue by yrobla** [fivetran/dbt_quickbooks#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When syncing a new transformation from scratch i got error with date transformation when date is None:

![image](https://github.com/fivetran/dbt_quickbooks/assets/2530861/4f68648c-e748-4e58-aff5-7a5c85be09ef)

### Expected behavior

Even if the date is null it should properly default to some date and cast to a valid type

### dbt Project configurations

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "noxu_dbt"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "noxu_dbt"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

### Package versions

packages:
  - package: fivetran/quickbooks
    version: [">=0.12.0", "<0.13.0"]

### What database are you using dbt with?

postgres

### dbt Version

1.6.6

jobs:
  # Give each job a unique name. The name will be displayed in the Fivetran dashboard once your jobs are imported.
  # Job names must be unique.
  - name: daily
    targetName: dev # The name of the target that will be used when running the job. If it's not specified, the target will be named 'prod'.
    schedule: 0 12 * * * # Define when this job should run, using cron format. This example will run every day at 12:00pm (according to your warehouse timezone). For help with cron formatting, visit https://crontab.guru/.
    # Optional timeout that limits the maximum run time of the job. You can specify only hours, only minutes or both, for example "6h", "2h30m", "30m"
    # The value can be in range from 30 minutes to 24 hours.
    # If timeout is not specified, the job will be terminated after 24 hours.
    timeout: 2h30m
    steps:
      - name: run models # Give each step in your job a name. This will enable you to track the steps in the logs.
        command: dbt run # Enter the dbt command that should run in this step. This example will run all your models. For a list of available commands visit https://docs.getdbt.com/reference/model-selection-syntax/.
      - name: test models
        command: dbt test # This example will run all your tests.

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @yrobla thank you for opening this issue and proactively working on a PR to address the issue you are seeing.

One quick question I have is do you know why the date field in the materialized General Ledger model would be None? My understanding is there should be at least one transaction and a corresponding date to pull from when the models are building. In this scenario, does your General Ledger model not have any records in it?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @yrobla I just wanted to bump the above. Are you still having this issue when leveraging the QuickBooks transformations? I want to make sure if this update is only necessary if there are no underlying transactions. If that is the case I would be less comfortable moving forward with your proposed changes, if that is not the case then I would like to discuss the changes further.

Let me know, thanks!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @yrobla I am going to mark this as stale and wont fix for the time being. If this issue continues to persist, please let us know and we may collaborate to understand the issue and address the problem. Thanks!
