### ISSUE TITLE
[Bug] Missing Account ID's on Invoice Lines in the General Ledger for a Shipping Product

### ISSUE THREAD

**Issue by mikerenderco** [fivetran/dbt_quickbooks#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The DBT job gets account ids from the invoice_line table but there are sales_item_item_id's that exist in this table but not in the item table itself. We have quite a few entries that have a sales_item_item_id = 'SHIPPING_ITEM_ID" and the dbt transformation uses this to assign an account to the item for the transaction, but for some reason this specific entry does not exist in our item table at all so the account_id in the general__ledger for this table comes in null. 

Is there any solution to pulling the Account ID on these GL entries when the base item table from Fivetran doesn't have a way to connect it to the invoice?

A good example is: transaction_ID: 105037

Select * from `qb_virginia.invoice_line` where invoice_id = '105037'; Select * from `qb_virginia.invoice_line` where sales_item_item_id='SHIPPING_ITEM_ID'; 
[invoice_line.csv](https://github.com/user-attachments/files/15536971/invoice_line.csv)
[GL-transaction-105037.csv](https://github.com/user-attachments/files/15537002/GL-transaction-105037.csv)

### Expected behavior

I would expect the GL to have the Account ID's for these transactions.

### dbt Project configurations

vars:
  using_credit_card_payment_txn: true # enable if you want to include credit card payment transactions in your staging models
  using_estimate: false # disable if you don't have estimates in QuickBooks
  using_invoice_bundle: false # disable if you don't have invoice bundles in QuickBooks
  using_purchase_order: true #enable if you want to include purchase orders in your staging models
  quickbooks_union_schemas: ['qb_retail','qb_virginia'] # use this if the data is in different databases/projects but uses the same schema name

### Package versions

packages:
  - package: fivetran/quickbooks
    version: [">=0.13.0", "<0.14.0"] # we recommend using ranges to capture non-breaking changes automatically

### What database are you using dbt with?

bigquery

### dbt Version

1.7

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by mikerenderco** [comment]
For now we have duplicated id= 57 in the invoice_lines table with the id = SHIPPING_ITEM_ID and that allows the DBT job to work correctly

**Comment by fivetran-avinash** [comment]
Hi @mikerenderco ,  thanks for reaching out!

Just so I can understand correctly, right now the issue you're experiencing is:

1) You have items properly set up in Quickbooks.
2) The base `item` table in Fivetran is not picking up those item ids, thus leading to the null account ids as it can't join on the `item_id`.

If this is the case, this is likely a connector issue [and you'll have to file a support ticket to fix this](https://support.fivetran.com/hc/en-us), but just want to confirm this before moving forward!

**Comment by mikerenderco** [comment]
Yes I think that is right.  I opened a ticket already with the five team
connector team.

Unfortunately we have no control over how the product is setup.  There is a
third party app the needs this product setup in this way in order for the
app to work.

You can close this though and I’ll use the patch that we applied.


Mike Lambeth
***@***.***
(775) 813-0944
renderanalytics.com

**Comment by fivetran-avinash** [comment]
(Sorry this comment got accidentally deleted, ignore this message, reposting for documentation.)

> 
> Hi Mike, thanks for reaching out!
> 
> Just so I can understand correctly, right now the issue you're experiencing is:
> 
>  1. You have items properly set up in Quickbooks.
> 2. The base item table in Fivetran is not picking up those item ids, thus leading to the null account ids as it can't join on the item_id. 
> 
> If this is the case, this is likely a connector issue and you'll have to file a support ticket to fix this <https://support.fivetran.com/hc/en-us>, but just want to confirm this before moving forward!

**Comment by fivetran-avinash** [comment]
Hey @mikerenderco , I'm seeing the ticket now! Thanks for opening that, they should hopefully be able to assist. 

Could you share the particular examples you shared with me above with support, and maybe they can see if there are any other reasons the item data is not showing up there, and maybe resolve the error for good. Unfortunately we are only responsible for the end model transformations, so if data isn't appearing, we don't want to apply a solution for a case that shouldn't even be happening.

Happy you were able to find a patch though!

**Comment by mikerenderco** [comment]
Thanks @fivetran-avinash - I did send these examples over to them asking why aren't they coming in as item id 57.  I was wondering if there was some issue in the coalesce statements on these in the DBT job but It sounds like the base api record is coming in strangely.  Appreciate your assistance on this.
