### ISSUE TITLE
[Bug] Issue with Invoice being assigned to the incorrect Account ID in the General Ledger

### ISSUE THREAD

**Issue by mikerenderco** [fivetran/dbt_quickbooks#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We have an invoice: 71442.  In the GL that is created by the DBT job it is being booked to account_id 136.  But all lines on the invoice have an sales_item_account_id of 329.  Except the subtotal line which is null and at the top of the 
stg_quickbooks__invoice_line all other lines are assigned to 329.  In models/transaction_lines/int_quickbooks__invoice_transactions.sql the account_id gets assigned with this code:  
case when invoice_lines.account_id is null
            then coalesce(items.income_account_id, items.expense_account_id, items.asset_account_id)
            else invoice_lines.account_id
                end as account_id,

136 is the items.income_account_id which means its satisfying the above case and going into the the first coalesce.  Something is wrong though with this statemenet because it should be evaluating every line and retrieving its appropriate account_id not applying the subtotal null accountid logic to all invoice lines.

Does that makes sense?  Attached are SS of BQ
[stg_quickbooks__invoice_line.csv](https://github.com/user-attachments/files/15809199/stg_quickbooks__invoice_line.csv)
[invoice_lines.csv](https://github.com/user-attachments/files/15809200/invoice_lines.csv)
[general_ledger.csv](https://github.com/user-attachments/files/15809201/general_ledger.csv)

### Expected behavior

invoice: 71442 lines should be going to account id 329 like they are in Quickbooks.

### dbt Project configurations

vars:
using_credit_card_payment_txn: true # enable if you want to include credit card payment transactions in your staging models
using_estimate: false # disable if you don't have estimates in QuickBooks
using_invoice_bundle: false # disable if you don't have invoice bundles in QuickBooks
using_purchase_order: true #enable if you want to include purchase orders in your staging models
quickbooks_union_schemas: ['qb_retail','qb_virginia'] # use this if the data is in different databases/projects but uses the same schema name

### Package versions

packages:

package: fivetran/quickbooks
version: [">=0.13.0", "<0.14.0"] # we recommend using ranges to capture non-breaking changes automatically

### What database are you using dbt with?

bigquery

### dbt Version

1.7

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-catfritz** [comment]
Hi @mikerenderco thanks for opening this issue! For the `quickbooks__general_ledger` model, the upstream model that determines the `account_id` is `int_quickbooks__invoice_double_entry`, and I think [this line](https://github.com/fivetran/dbt_quickbooks/blob/main/models/double_entry_transactions/int_quickbooks__invoice_double_entry.sql#L122) is why I think you're seeing the wrong `account_id`. The `sales_item_account_id` is last in the coalesce list. Where would you say that this field should be prioritized in the coalesce list?

**Comment by mikerenderco** [comment]
Thanks @fivetran-catfritz - after looking at this transaction in quickbooks it looks like our client is using an invoice where they should be using  a Journal Entry.  I would hate to modify this Coalesce as it works for all other lines.  But let me confirm that and we will get back to you.

**Comment by mikerenderco** [comment]
Hi @fivetran-catfritz - So this one is strange one.  It looks like it all stems from the raw invoice_lines table coming out of fivetran has an item_id of 1.  But when you actually look at the invoice in Quickbooks there are no products/services assigned on the invoice.  We have two instances like this and another instance where the invoice is exactly the same but it doesn't have the item_id  populated and is working correctly. 

It seems like a fivetran connector issue but I'm guessing its coming out of the API that way.  Since these are historical transactions that won't be touched again i went ahead and just cleared out the items = 1 on these two transactions in bigquery table and now the GL balances.  

Ill close this ticket as it isn't a dbt issue.

**Comment by fivetran-catfritz** [comment]
@mikerenderco Very interesting--thank you for sharing your findings. Thanks for closing, however feel feel to ping us again if you have any further questions!
