### ISSUE TITLE
[Bug] Invoice Double Entry not filtering inactive/sub account AR

### ISSUE THREAD

**Issue by brandonrf94** [fivetran/dbt_quickbooks#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In most places of your transforms you are selecting and filtering the AR accounts.
https://github.com/fivetran/dbt_quickbooks/blob/e604697a51880e2f57bc89606517bb499eb6a017/models/double_entry_transactions/int_quickbooks__invoice_double_entry.sql#L93

This also needs to be done here, if someone deletes an AR account then you'll start duplicating rows.

### Expected behavior

Filter to one active AR account.

### dbt Project configurations

Any

### Package versions

Any

### What database are you using dbt with?

snowflake

### dbt Version

Any

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @brandonrf94 thanks for opening this issue!

I see what you are saying that a deleted AR account could be brought through via this logic. I do also see how we are doing this for all other models where we bring in AR accounts and we should be applying the same logic for invoices. We will need to apply the following condition for the invoice double entry model:

https://github.com/fivetran/dbt_quickbooks/blob/e604697a51880e2f57bc89606517bb499eb6a017/models/double_entry_transactions/int_quickbooks__credit_memo_double_entry.sql#L39-L41

This is a fairly low lift update and we can easily integrate this into the WIP branch @fivetran-avinash is currently working on within PR #134. I will coordinate with our team to integrate this update in the next upcoming release for early next week. 

Thanks again @brandonrf94 for helping raise these issues across the dbt package and helping us address them 😄

**Comment by fivetran-avinash** [comment]
Hi @brandonrf94 ! Our latest release of `dbt_quickbooks` is [live on the hub](https://hub.getdbt.com/fivetran/quickbooks/latest/). It should have gone ahead and fixed this issue.

Please check it out and let us know if you have any issues or questions. Thanks again for your great collabration as always!
