### ISSUE TITLE
[Bug] Division by zero errors originating from intermediate deposit models

### ISSUE THREAD

**Issue by fivetran-avinash** [fivetran/dbt_quickbooks#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Quickstart customers were experiencing division by zero errors after upgrading to the recent release of the package. This is because in [the v0.14.0 release](https://github.com/fivetran/dbt_quickbooks/releases/tag/v0.14.0) we introduced changes to our intermediate deposit models to support multicurrency that required a division operation on `total_amount` from the `deposits` source. But we didn't account for the possibility that the denominators can be zero. We will introduce functionality that sets these values to null.

### Relevant error log or model output

```shell
"Database error in model `int_quickbooks__deposit_double_entry`... division by zero"

"Database error in model `quickbooks__expenses_sales_enhanced`... division by zero"
```

### Expected behavior

Successful compilation when the `total_amount` for a deposit is zero. 

### dbt Project configurations

```
models:
  quickbooks:
    +materialized: table
    +schema: quickbooks
    double_entry_transactions:
      +schema: quickbooks_intermediate
      +materialized: table
    transaction_lines:
      +materialized: ephemeral ##this will generate the error in the end model--materializing it in the table will fix the issue.
    intermediate:
      +materialized: ephemeral
```

### Package versions

packages:
  - package: fivetran/quickbooks_source
    version: [">=0.10.0", "<0.11.0"]

### What database are you using dbt with?

snowflake, bigquery

### dbt Version

1.7.16

### Additional Context

See Height ticket T-759329

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will probably need assistance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
@fivetran-avinash is this issue good to be closed out?

**Comment by fivetran-avinash** [comment]
@fivetran-joemarkiewicz yes, thanks for catching!
