### ISSUE TITLE
[Bug] Bank transfers between 2 accounts in 1 QBO entity are not showing accurate FX rates applied.

### ISSUE THREAD

**Issue by brandonrf94** [fivetran/dbt_quickbooks#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

![image](https://github.com/user-attachments/assets/69ac4fa7-b71a-4a1b-a877-96af57b3ffef)
![image](https://github.com/user-attachments/assets/0dbf8ed6-f3fd-450b-b5f6-9fa49fb4fc43)

QBO is showing the amounts in CAD for this CAD to USD transfer, but the fivetran table is showing the USD amounts

### Expected behavior

Amounts in fivetran dataset matches quickbooks ux.

### dbt Project configurations

Quickstart

### Package versions

Quickstart (most recent)

### What database are you using dbt with?

snowflake

### How are you running this dbt package?

Fivetran Quickstart Data Model

### dbt Version

NA

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance.
- [X] No.

**Comment by fivetran-avinash** [comment]
Hi @brandonrf94, thanks for reporting this. Just to be clear, is this issue coming from a Quickstart data model, or within a connector table? The screenshot of the conversion issue appears to be coming from the raw transfer table. 

If it's the latter, [the best approach would be to file a support ticket with Fivetran](https://support.fivetran.com/hc/en-us) to see why the exchange rate is not being properly applied, as our team only focuses on issues at the data model level.

If the issues are occurring downstream in the end models themselves, happy to investigate! Let us know if you have any questions.

**Comment by brandonrf94** [comment]
The issue is the quickstart model is assuming the exchanged amount is the same as the amount. The transfer needs to have the fx amount applied.
________________________________

**Comment by fivetran-avinash** [comment]
Hey @brandonrf94 , thanks for submitting this issue! After further discussion I'm glad we were able to agree this is likely a connector issue. Let me know if you need any help with the support ticket. 

I will make this as won't do (for the solutions team, the Fivetran support ticket will have a different workflow), and close this ticket out.

**Comment by pranitwarehows** [comment]
@brandonrf94 atleast hide the PII data before sharing transactions man
