### ISSUE TITLE
FEATURE - general ledger unioning

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_quickbooks#26]
adapt this! https://github.com/fivetran/dbt_ad_reporting/blob/master/macros/get_staging_files.sql

**Comment by fivetran-avinash** [comment]
@fivetran-jamie @fivetran-joemarkiewicz Was this macro updated to https://github.com/fivetran/dbt_ad_reporting/blob/main/macros/get_enabled_packages.sql?

**Comment by fivetran-joemarkiewicz** [comment]
@fivetran-avinash, it was - however, I think the old macro may fit the QuickBooks use case a bit better.

https://github.com/fivetran/dbt_ad_reporting/blob/v0.8.0/macros/get_staging_files.sql

**Comment by fivetran-avinash** [comment]
Part of the `v0.7.0` release, so we can go ahead and close this.
