### ISSUE TITLE
FEATURE - Union Schemas Ability

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_quickbooks#28]
**Are you a Fivetran customer?** 

Fivetran identified request

**Is your feature request related to a problem? Please describe.**
 
A number of customers have identified that it would be beneficial to run this package for a number of quickbooks schemas. This request would be to add the same functionality within [dbt_shopify](https://github.com/fivetran/dbt_shopify/pull/16) to this quickbooks package. This will allow users to union multiple schemas using this package.

**Describe the solution you'd like**
 
A user of this package is able to call out a number of quickbooks schemas in their `dbt_project.yml` and the package is able to union them and create a union identifier so they may be used in downstream models.

**Describe alternatives you've considered**

Martin from Montreal Analytics highlighted the best alternative to this feature in his [Medium article](https://medium.com/montreal-analytics/how-to-use-the-shopify-dbt-package-by-fivetran-with-multiple-shops-eb4cea326ee0). It would be great however to integrate this functionality into the package. 

**Additional context**

This should result in a breaking change as it would be a massive feature addition.

**Comment by fivetran-avinash** [comment]
[This is fixed with the `0.7.0` release](https://github.com/fivetran/dbt_quickbooks/releases/tag/v0.7.0), so will close this issue.
