### ISSUE TITLE
Add variable for not using "Sales Receipts"

### ISSUE THREAD

**Issue by bbirand** [fivetran/dbt_quickbooks#3]
I really like that there are variables that control which QBO features are used. I think a big part of the issue is that FiveTran doesn't create empty tables. 

Can you add another switch for the "Sales Receipts", which we don't use?
  Object 'FIVETRAN_DATABASE.QUICKBOOKS.SALES_RECEIPT_LINE' does not exist or not authorized.
  Object 'FIVETRAN_DATABASE.QUICKBOOKS.SALES_RECEIPT' does not exist or not authorized.

**Comment by fivetran-kristin** [comment]
Hi @bbirand - we will look into doing this and get back to you here. Thanks for the suggestion!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @bbirand 👋 

Thanks for bringing the sales_receipt variable to our attention. I have been able to create a new branch for the [dbt_quickbooks_source](https://github.com/fivetran/dbt_quickbooks_source/tree/sales_receipt_var) and [dbt_quickbooks](https://github.com/fivetran/dbt_quickbooks/tree/sales_receipt_var) packages that incorporate the `using_sales_receipt` variable which allows you to deactivate the sales receipt models if you do not use them without impacting downstream models.

Before we merge these changes to master we would really appreciate your help in testing the new branch to ensure you are seeing your expected results. To test the changes I made you can update your `packages.yml` file to have the below git dependency:
```
packages:
    - git: https://github.com/fivetran/dbt_quickbooks.git
      revision: sales_receipt_var
      warn-unpinned: false
```

Once you save this change to your `pakcages.yml` file, you may add the below variable to your `dbt_project.yml` file to declare the `using_sales_receipt` variable as `false` and therefore deactivate the sales receipt models.
```
vars:
  quickbooks:
    using_sales_receipt:  False

  quickbooks_source:
    using_sales_receipt:  False
```
You can run the below commands to clear the old package and install the working branch.
```
dbt clean && dbt deps
```
Finally, you may then execute `dbt run` and let us know if you encounter any errors, or if it is succesful for you.

Thanks!

**Comment by bbirand** [comment]
I actually ended up creating a sales receipt object just to fill that table... I’ll check what happens when I delete them again.  

--  
Berk Birand

**Comment by fivetran-joemarkiewicz** [comment]
Hi @bbirand were you able to try the working branch after the tables were deleted? If this worked for you I can open a PR for the working branch to incorporate the changes. 

Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
@bbirand the recent release of the [QuickBooks package](https://hub.getdbt.com/fivetran/quickbooks/latest/) fixes this issue while also adding some other additional features! You may now disable the sales_receipt tables with the `using_sales_receipt: False` variable!

Feel free to install the new release as a dependency in your dbt_project and your issue will be resolved.
```
packages:
  - package: fivetran/quickbooks
    version: 0.1.2
```
