### ISSUE TITLE
BUG - Fails when encountering 'SHIPPING_ITEM_ID' values in sales_receipt_line.sales_item_item_id

### ISSUE THREAD

**Issue by ligfx** [fivetran/dbt_quickbooks#37]

**Comment by fivetran-joemarkiewicz** [comment]
Hi @ligfx would you be able to provide a bit more context to your error? It looks like there was no description provided in the Issue.

Based off your title, I think the Issue opened in our [dbt_quickbooks_source](https://github.com/fivetran/dbt_quickbooks_source/issues/23) repo may be similar to what you are experiencing. If that is the case, would you be willing to attempt to run the following version of the package and let me know if you still experience the failure?
```yml
packages:
  - git: https://github.com/fivetran/dbt_quickbooks.git
    revision: bugfix/evancole-untitled-casting
    warn-unpinned: false
```

**Comment by ligfx** [comment]
Hi @fivetran-joemarkiewicz, yes, it's the same issue. The branch you recommended works, thank you!

**Comment by fivetran-joemarkiewicz** [comment]
That's great to hear @ligfx!!

I will be meeting with the creator of the Issue linked next Thursday. You can most likely expect an official release with this fix applied by the end of next week. For the time being, feel free to use the branch and I will leave this issue open until the release is live.

**Comment by ligfx** [comment]
Awesome, thanks @fivetran-joemarkiewicz !

**Comment by fivetran-joemarkiewicz** [comment]
@ligfx this issue will now be resolved in the latest version of the dbt_quickbooks `v0.5.0` release! You can expect this release to be live at the top of the hour.

Feel free to open another issue if you encounter any errors, or open a FR if you would like to see more functionality from the package 😄
