### ISSUE TITLE
[Bug] Balance Sheet Transactions Duplicating 

### ISSUE THREAD

**Issue by aufdenkamp** [fivetran/dbt_quickbooks#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We are experiencing duplicate general ledger entries in our balance sheet, causing it to not match our Quickbooks reporting. 

What I'm seeing is that for each duplicate, there is one coming from each `Transaction_Source` of `journal_entry` and `transfer`. It also appears that the duplicate entries have a different `Transaction_Index` (one has an index of 0, the other an index of 1). There is only one duplicate of each duplicated transaction. 

### Relevant error log or model output

```shell
![image](https://user-images.githubusercontent.com/97621944/186465582-bc3784c7-4b15-4467-9b59-5319f7bf5142.png)
```

### Expected behavior

I would expect only one value per transaction - either from transfer or journal entry. 

### dbt Project configurations

  quickbooks:
        #Variables if your company utilizes the below parent and child transactional tables.
    using_address:        True
    using_bill:           True
    using_credit_memo:    True
    using_department:     True
    using_deposit:        True
    using_estimate:       True
    using_invoice:        True
    using_invoice_bundle: True
    using_journal_entry:  True
    using_payment:        True
    using_refund_receipt: False
    using_transfer:       True
    using_vendor_credit:  True
    using_sales_receipt:  False
    using_purchase_order: False

### Package versions

0.5.0, also tested the subindices fix prior to release

### What database are you using dbt with?

snowflake

### dbt Version

1.0

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by aufdenkamp** [comment]
![image](https://user-images.githubusercontent.com/97621944/186474207-3370fa4e-8ede-4d0a-8d24-7fe8675fbee4.png)

**Comment by aufdenkamp** [comment]
Do we just need to flip `using_transfer` to `false`?

**Comment by aufdenkamp** [comment]
I looked into this a little bit more - this is related to deleted transactions in Quickbooks. For example, in our Quickbooks instance, all of the `transfer` items in the above image are "deleted", but they are still coming through in the data, even after a historical resync.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing this information @aufdenkamp!

Is there a way in the source data you are able to determine that these transactions are deleted? Or are you only able to determine as such after viewing direction in QuickBooks?

**Comment by aufdenkamp** [comment]
I have only been able to determine that they are deleted after viewing Quickbooks. I could not find any indication in the source data that they were deleted.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing @aufdenkamp, let me do some digging to see if I can find a way to determine this in the source data. 🤔

**Comment by aufdenkamp** [comment]
@fivetran-joemarkiewicz Any luck?

**Comment by fivetran-joemarkiewicz** [comment]
Non yet 😢. I would recommend opening a ticket with our [Support Team](https://support.fivetran.com/hc/en-us) so our engineering team can take a closer look and hopefully find a way to understand if a transaction is deleted.

I'll keep looking in the meantime.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @aufdenkamp just wanted to check in if you were able to reach out to customer support?

**Comment by aufdenkamp** [comment]
I have reached out - sounds like the issue in the Transfers table will be
resolved today? Still working with support on some additional items.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @aufdenkamp came back across this ticket and assume that everything is resolved on your end. Closing out this GitHub issue. 

Feel free to reopen the issue if you feel there is more to discuss on this original issue. 😄
