### ISSUE TITLE
[Feature] README Updates

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_quickbooks#52]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

This packages README is not currently inline with our existing standards. It would be ideal for this repo to see README updates to be in line with our current documentation guidelines.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

During these updates, we should also add the `identifier` variables and ensure the `integration_tests/dbt_project.yml` references the identifiers as well.

**Comment by fivetran-avinash** [comment]
Part of the `v0.7.0` release, so this issue can be closed.
