### ISSUE TITLE
[Bug] Duplicating Accounts Receivable entries in the ledger

### ISSUE THREAD

**Issue by mel-restori** [fivetran/dbt_quickbooks#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I'm seeing duplicate Accounts Receivable entries in the ledger, and I think it's coming from [this cross join](https://github.com/fivetran/dbt_quickbooks/blob/76f324f566c83b2972498d137026497319b733e6/models/double_entry_transactions/int_quickbooks__payment_double_entry.sql#L72) to the `account` table. 

It looks like a [fix](https://github.com/fivetran/dbt_quickbooks/commit/67c608629de1ccdba2defdc824546443bfca35ee) recently went in to try to account for duplication, but it didn't solve our use case since we have two accounts that satisfy all three conditions in the where clause: 
```
where account_type = 'Accounts Receivable'
        and is_active
        and not is_sub_account
```

### Expected behavior

I expect a payment to be linked to a single account

### dbt Project configurations

vars:
    quickbooks_database: adsk-fivetran-prod
    
    using_address:        true
    using_bill:           true
    using_credit_memo:    true
    using_department:     true
    using_deposit:        true
    using_estimate:       true
    using_invoice:        true
    using_invoice_bundle: true
    using_journal_entry:  true
    using_payment:        true
    using_refund_receipt: true
    using_transfer:       true
    using_vendor_credit:  true
    using_sales_receipt:  true
    using_purchase_order: true
    using_credit_card_payment_txn: true

### Package versions

packages:
  - git: https://github.com/fivetran/dbt_quickbooks.git
    revision: feature/credit-card-payments
    warn-unpinned: false

(NOTE: I know that's a test branch for a different issue, but the relevant code for the cross join is the same)

### What database are you using dbt with?

bigquery

### dbt Version

n/a

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @mel-restori thanks so much for opening this issue and I am sorry to see you are still running into the duplicates issue.

That is quite interesting that you have multiple accounts that satisfy all three of our conditions in the model. Are the accounts that satisfy the conditions duplicates, or are they their own distinct accounts? Would you be comfortable sharing the accounts on your end that satisfy the where clause? This may help us narrow down what needs to be adjusted within the where clause or the cross join.

Thanks!

**Comment by mel-restori** [comment]
Hi Joe! I’m consulting for a company that in turn works with multiple clients so unfortunately I’m a couple steps removed. But they seem like distinct accounts. There are only 2 transactions in one of the accounts (both with amounts of $0), and tellingly the account has the text “not used” within its title. But the Quickbooks UI can tell them apart and correctly allocate transactions across the accounts.
On my end I’ll see what we are able to share. What details about the accounts would help you investigate? The full rows in `account` for those two accounts?
Thanks again!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing @mel-restori! The fact that their names have `don't use` and are of $0 is making me wonder if these should be listed as `active`?

I think if these accounts are listed as inactive then the logic within the package should be able to properly allocate the transactions and build the end models. Do you know if updating the accounts status would be a possibility or if it is appropriate from your customers point of view? From my understanding, there should only be one parent Accounts Receivable account, but I may be mistaken.

**Comment by mel-restori** [comment]
Thanks @jonatfivetran ! I hear you, but the account is in fact active and the Quickbooks UI seems to distinguish between the two accounts just fine. According to [this](https://quickbooks.intuit.com/learn-support/en-us/other-questions/multiple-accounts-payable-and-accounts-receivable-in-qbo/00/958028) post, it's recommended, but not required, to have only one such account (same with A/P accounts).

For our immediate use case, I'll ask to see whether we can ask the client to de-active the "not used" account. But we'll need a more robust solution if multiple accounts are, in fact, allowed by QB, which it looks like they are.

Have you considered testing for number of accounts for those you're expecting to be unique and throwing errors (/warnings) or having different ways of handling multiples instead of a cross join?

Thanks again!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing that forum post. That is really helpfully that QuickBooks mentions there in fact can be multiple AP/AR accounts. Although they mention this isn't recommended, it looks like they will allocate transactions to the default account.

I was a bit nervous to move away from the cross join as I am unsure what AP/AR account to associate the transactions with. However, this idea of the default account may allow us to remove the cross join and do a direct join on the default account. Do you know if there is any indication within your source data that highlights which AR account in this case is the default one? Similarly, is there anything in QBO that highlights this default account by chance?

**Comment by mel-restori** [comment]
sadly, no, I can't tell at all either in QB or in the imported data. 
I'm attaching a csv of the columns for those 2 accounts from the `account` table. (Note I changed the balance amount on the "correct" account for client privacy, left it as "0" for the "not used" account). The only things I see different is that the "not used" account has a null description, but guessing that isn't something we can count on.
Also the sync token field is different but I'm guessing that's a Fivetran column?

I went into QB and pretended to add a new AR account and nothing within the QB UI warned me not to have multiple accounts or asked to set which is a default (attaching screenshot).

[AR accounts.csv](https://github.com/fivetran/dbt_quickbooks/files/9985113/AR.accounts.csv)

<img width="549" alt="Screen Shot 2022-11-10 at 2 40 11 PM" src="https://user-images.githubusercontent.com/12188105/201221634-59985924-f66b-4200-bd72-3f3ef08e1fb7.png">

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much @mel-restori this is really helpful. Do you know if there is any indication within the corresponding payment transaction if it highlights which AR account it should be attached to?

In the meantime, I am going to loop up with our product manager for the QuickBooks connector to see if they have come across this type of behavior in other environments.

**Comment by mel-restori** [comment]
I'll dig around!

**Comment by mel-restori** [comment]
I'm sorry, I don't see any way to link to the correct account :(  It does seem like some key is missing since Quickbooks UI can differentiate.
Thanks!

**Comment by mel-restori** [comment]
Hi @fivetran-joemarkiewicz, did you hear back from the product manager? This is still causing significant discrepancies. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @mel-restori I have not been able to discover a solution with the product manager just yet. In the interim, you may be able to modify this specific model for your use case to remove the duplicates.

If you want, you can actually disable the model in question, rebuild it within your project (naming it the same as the package model), copy/paste the code from the package, and then make that small change to the where clause to only bring in the intended AR account. 

This could solve your problem immediately while still allowing us to dig into this a bit further to find a permanent solution.

**Comment by mel-restori** [comment]
thanks for that suggestion! How would we disable the model? would that be by setting `using_payment` to false? if so, would that variable impact any other model?

then we'd create our own `models/double_entry_transactions/int_quickbooks__payment_double_entry.sql` ?

**Comment by fivetran-joemarkiewicz** [comment]
To disable the model you would actual disable the model itself as opposed to the variable. You are correct that if you disable the variable then it will impact the totals downstream.

To disable to model you can include the following in your root (not the package) dbt_project.yml:
```yml
models:
  quickbooks:
    double_entry_transactions:
      int_quickbooks__payment_double_entry:
        +enabled: false
```

This will disable the package model. Then within your root (not the package) `models/` folder, you can create a new model with the exact same name as the model name in the package `int_quickbooks__payment_double_entry.sql`. In this new model, you can copy/paste the sql from the package model and make whatever edits you want. When the package is run, it will instead use your custom model in place of the package one.

Here is a pic of what it looks like on my end when I configured for this to work.
![image](https://user-images.githubusercontent.com/74217849/202045485-366c5888-7239-4ee9-8406-b342ad89824f.png)

**Comment by fivetran-joemarkiewicz** [comment]
As a solution was uncovered and the initial error has been addressed, I will mark this ticket as closed.

However, I will label the issue as a `wontfix` as it was not an update that was pushed out to all package users. That being said, if another user comes across this same issue then they may use the same approach outlined above to reach the desired fix.

Please comment in this ticket if you leverage this solution. If we find a number of users are needing this workaround then we can evaluate at a grander scale what it would look like to implement an adjustment for all package users.

**Comment by CPAanalytics** [comment]
I have the same issue.  The workaround of specifying the AR account you want the query to use doesn't work because journal entries specify the other accounts ultimately resulting in incorrect balance sheet balances.  There appears to be missing information on the invoice table that would specify the correct AR account to apply the debits to.
