### ISSUE TITLE
[Feature] Break out Net Income from Retained Earnings

### ISSUE THREAD

**Issue by mel-restori** [fivetran/dbt_quickbooks#57]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Today, Fivetran combines Net Income and Retained earnings into one line item (called "Net Income / Retained Earnings Adjustment"), but the QuickBooks UI breaks them out separately. It would be helpful for comparisons for them to be broken out. Relevant code is [here](https://github.com/fivetran/dbt_quickbooks/blob/main/models/intermediate/int_quickbooks__retained_earnings.sql).

Thank you!

Attaching redacted screenshot from QuickBooks
<img width="419" alt="Screen Shot 2022-11-23 at 9 46 28 AM" src="https://user-images.githubusercontent.com/12188105/203653930-42aa0983-a16d-40df-bc8e-dfdde199af2e.png">

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @mel-restori I think it may be best if we instead renaming the "Net Income / Retained Earnings Adjustment" field. This field is generated by capturing the Net Income adjustment from the relevant period. This can sometimes be referred to as the retained earnings adjustment as well. However, if you have your own Retained Earnings account (which is seems you do) then I could see the naming of this field to be duplicative.

Can you confirm that your end models product a Retained Earnings record for a given period as well as a Net Income / Retained Earnings Adjustment record? If so, then I think this should be an easy feature to roll into our next update to rename the field to `Net Income Adjustment`.

**Comment by mel-restori** [comment]
Hi @fivetran-joemarkiewicz thanks for following up. 
I'll first admit that I really don't know much about accounting, figuring it out on the fly while I reconcile the Quickbooks UI balance sheet from the Fivetran data model balance sheet. But in Quickbooks, it doesn't look like "Retained Earnings" is a separate account - and it's the only value that I can't click on to drill down into. I was able to figure out that that amount matches the sum of net income from previous time periods, though. So it seems like it's how it carries forward the net income from previous years and then keeps the "net income" row only for the time period selected in the report. 
I got to this through trial an error so maybe what I'm saying doesn't make sense.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for this insight @mel-restori! Based on this discovery I think my initial idea would probably be the best course of action to make the record more clear. These "Net Income / Retained Earnings Adjustment" records are simply calculating the "net income" for the periods and factors it into the current BS period. Therefore, renaming the field to just be "Net Income Adjustment" would be more appropriate in my eyes and also allow for it to not be confused with a true Retained Earnings account.

**Comment by mel-restori** [comment]
@fivetran-joemarkiewicz  that sounds right, but we also need to get the net income from previous periods in order to match the balance sheet in the Quickbooks UI

**Comment by fivetran-avinash** [comment]
Hi @mel-restori, I'm working on this feature now. Could you elaborate on what you mean about the balance sheet not matching net income from previous periods?  It seemed in the previous comment that this solution would work, or do you think there is additional logic required to get the matching you're looking for?

**Comment by fivetran-avinash** [comment]
Thanks for the context @mel-restori! 

We have fixed the field to correctly reflect "Net Income Adjustment". We plan on merging this into our `main` branch in the New Year! You can view the PR for now if you want to see what it looks like. https://github.com/fivetran/dbt_quickbooks/pull/66

We will try to address creating the Retained Earnings definition you're looking for in a future sprint. 

Le tme know if you have any questions! Happy to assist.

**Comment by mel-restori** [comment]
thanks!

**Comment by fivetran-avinash** [comment]
Hi @mel-restori ! We have deployed this fi[x in the `0.7.0` version of our package.](https://github.com/fivetran/dbt_quickbooks/releases/tag/v0.7.0)  If you upgrade your `packages.yml` to any version of 0.7.0 or above ([we recently deployed `0.8.0`](https://github.com/fivetran/dbt_quickbooks/releases/tag/v0.8.0)) you should be able to see "Net Income Adjustment" correctly reflected.

We are going to close this issue, but if have any questions, thoughts or feedback, please let us know in this issue!

Cheers.
