### ISSUE TITLE
[Bug] Invoice discounts aren't included as line items in the general ledger

### ISSUE THREAD

**Issue by SellJamHere** [fivetran/dbt_quickbooks#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Missing invoice amounts cause an incorrect profit and loss report, as the profit is inflated by the discounted amount.

Quickbooks supports a percentage-based discount on invoices. This discount is present as a line item in `stg_quickbooks__invoice_line`, but it is filtered out in the `int_quickbooks__general_ledger_balances` calculation.

The discount line is filtered out because it has a `discount_account_id` instead of a `sales_*_id` or `account_id`.

```
WHERE coalesce(invoice_lines.account_id, invoice_lines.sales_item_account_id, invoice_lines.sales_item_item_id, invoice_lines.item_id) is not null
```

[discount_invoice_example.csv](https://github.com/fivetran/dbt_quickbooks/files/10126490/discount_invoice_example.csv)

### Expected behavior

I expect the invoice discount to be included in the invoice calculations so that the resulting P&L and balance sheet show the correct values.

### dbt Project configurations

    using_address: true
    using_bill: true
    using_credit_memo: true
    using_department: true
    using_deposit: true
    using_estimate: true
    using_invoice: true
    using_invoice_bundle: true
    using_journal_entry: true
    using_payment: true
    using_refund_receipt: true
    using_transfer: true
    using_vendor_credit: true
    using_sales_receipt: true

### Package versions

packages:
  - package: fivetran/quickbooks_source
    version: [">=0.5.0", "<0.6.0"] 

### What database are you using dbt with?

databricks

### dbt Version

Unsure. I tested directly in Fivetran.

### Additional Context

I will prepare a PR with a potential fix. It resolves the issue, but I'd like to review it with the team to determine if it's sufficiently generalized.

_Edit: PR https://github.com/fivetran/dbt_quickbooks/pull/60_

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @SellJamHere 👋 Thanks so much for opening this informative issue. 

We had not encountered invoices with discounts before which is why I can see you are currently running into that issue on your end. I also really appreciate your taking the first go at opening the PR to address this issue. You are actually opening this at a great time as @fivetran-avinash is currently working on addressing a number of the open FRs for QuickBooks and this could be a great issue to address in these updates.

I have a feeling we will have more questions and clarifications when reviewing the PR linked above. Thanks again for helping keep our package up to date and you should hear from us in the coming week within your PR!

**Comment by SellJamHere** [comment]
Thanks @fivetran-joemarkiewicz !

**Comment by fivetran-avinash** [comment]
Hi @SellJamHere! Thanks for the Issue and PR submission.

I see you chose to apply the discount straight to the invoice line to show the final invoice figures (https://github.com/fivetran/dbt_quickbooks/pull/60/files). However, I think you're applying the discount to every line item in the invoice? While that might work for his particular example, I'm not certain we can assume that this will always be the case.

Also had two additional questions: 
1) You brought in a left join for `items` in your first new CTE, but you don't bring any fields from `items` into the model.  What was the reason for that join?
2) There is a third union you make in the double entry model for discounts, but I don't think you make an equivalent double entry for those cases.  What was the reason for that?

**Proposed solution:** 
I think it makes sense to keep every line piece separate (like discount) and then it gets calculated independently later on (although maybe we make it a negative amount if it's a discount as you did). So i'm wondering if just a coalesce to bring in the discount ids makes more sense, bringing in those discount line items in, and then you can apply similar custom logic for these models within your business intelligence solutions?

Let me know if this proposal makes sense or if there's any issues with my proposed approach! Happy to talk through it.

**Comment by toppare** [comment]
hi, I am having the same problem do you have any timeline to fix this?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @toppare thanks for bumping this issue. We will likely be picking this up in our upcoming sprint (starting mid next week). We will post back here with more details as we work on addressing the invoice discounts.

**Comment by SellJamHere** [comment]
Thanks for carrying this though, @fivetran-joemarkiewicz ! I'm excited to get back on main 🎉
