### ISSUE TITLE
[Bug] <General Ledger Missing Credit Card Payments>

### ISSUE THREAD

**Issue by rebeccaanneblock** [fivetran/dbt_quickbooks#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Credit Card Payment transaction type is not flowing into the general ledger, producing a running balance which does not match the true running balance. This is evident when comparing the running balance with the current account balance. It is also apparent when comparing to the general ledger report in the quickbooks UI.

### Expected behavior

Credit Card Payments as seen in the `credit_card_payment_txn` base table should be included in the general ledger.

### dbt Project configurations

Using the Fivetran Quickstart Transformation

### Package versions

Fivetran Quickstart

### What database are you using dbt with?

redshift

### dbt Version

Fivetran Quickstart

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @rebeccaanneblock thanks for opening this issue! 

Do you currently have the `using_credit_card_payment_txn` variable set to `true` (it is false by default)? I believe this should address the issue you are experiencing.

You can see a list of all our variables in the [README](https://github.com/fivetran/dbt_quickbooks#step-4-enablingdisabling-models). Let me know if this does the trick!

**Comment by rebeccaanneblock** [comment]
@fivetran-joemarkiewicz thanks for such a quick reply! Is there a way to edit those variables in the fivetran quickstart interface () or would i have to go through the dbt setup to do so?
![image](https://user-images.githubusercontent.com/79816955/223824474-b254a6b5-c278-490e-90fe-72dfd91d0e12.png)

**Comment by fivetran-joemarkiewicz** [comment]
Hi @rebeccaanneblock I don't believe there is a way to edit them within the Quickstart menu. My understanding is that the Quickstart integration should set the variables for you automatically. Therefore, if you have the credit card payments source table, then it should set that variable for you.

My team doesn't handle the integration directly, so I would actually encourage you to open a [support ticket](https://support.fivetran.com/hc/en-us) for our engineering team to take a look and see how this variable can be set in your Quickstart integration.

**Comment by rebeccaanneblock** [comment]
Thanks @fivetran-joemarkiewicz! I'll send them a message.

**Comment by fivetran-joemarkiewicz** [comment]
Sounds great! For the time being, I will close this issue as it most likely is something that needs to be addressed within the Quickstart integration and not the package code. 

Please feel free to reopen if you want to discuss further!
