### ISSUE TITLE
calendar date in the profit and loss model should be the last day of the month

### ISSUE THREAD

**Issue by caffeinebounce** [fivetran/dbt_quickbooks#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

From a financial reporting perspective, items in each row include items through the last day of the month. However, the profit and loss model pulls through the period_first_day instead of the period_last_day from the GL by period table, which seems a lot more logical. 

### Relevant error log or model output

```shell
/
```

### Expected behavior

/

### dbt Project configurations

/

### Package versions

/

### What database are you using dbt with?

snowflake

### dbt Version

/

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-reneeli** [comment]
This has been addressed in the latest release (v0.13.0) of this package. As such we'll be closing this issue out!

**Comment by fivetran-reneeli** [comment]
* Addressed in v0.13.1
