### ISSUE TITLE
Cash flow statement drops cash_beginning_value and the cash_net_period for the first row of a particular account

### ISSUE THREAD

**Issue by caffeinebounce** [fivetran/dbt_quickbooks#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The final CTE for quickbooks__cash_flow_statement should coalesce 0 with lag(cash_ending_period) since the value for the first row will always be null.

Corrected code:

final as (
    
    select cash_flow_classifications.*,
        coalesce(lag(cash_ending_period) over (partition by account_id, class_id, source_relation order by cash_flow_period), 0) as cash_beginning_period,
        cash_ending_period - coalesce(lag(cash_ending_period) over (partition by account_id, class_id, source_relation order by cash_flow_period), 0) as cash_net_period
    from cash_flow_classifications
)

### Expected behavior

Every row should have a value, even if 0 

### dbt Project configurations

/

### Package versions

/

### What database are you using dbt with?

snowflake

### dbt Version

1.4.1

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @caffeinebounce thanks for raising this and I agree with you that a coalesce to 0 would be ideal here! We are actually planning to include some changes to the QuickBooks package in the next few days and I think this would be a great fix to include.

I noticed you are open to contributing. If you would like, you can open a PR with this fix and I will integrate it into the next wave of changes.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for helping with this @caffeinebounce! This is now live in the latest version of the package!

Closing this issue, please feel free to reopen if the issue still persists.
